services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      HOST: "db"
      REDIS_HOST: "redis"
    depends_on:
      - db
      - redis
  

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: foodtracker_app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pushaka2014
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: